version: 2.1

executors:
  go-executor:
    docker:
      - image: golang:latest

jobs:
  test:
    executor: go-executor
    steps:
      - checkout

      - run:
          name: Install staticcheck and gosec
          command: |
            go install honnef.co/go/tools/cmd/staticcheck@latest
            go install github.com/securego/gosec/v2/cmd/gosec@latest

      - run:
          name: Run tests
          command: |
            make test

workflows:
  test_workflow:
    jobs:
      - test
